<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>GestureSign.ExtraPlugins.ClipboardMatch</RootNamespace>
    <AssemblyName>GestureSign.ClipboardMatch.Plugin</AssemblyName>
    <Title>GestureSign.ExtraPlugins.ClipboardMatch</Title>
    <Description>ClipboardMatch Plugin</Description>
    <Company>TransposonY</Company>
    <Product>GestureSign.ExtraPlugins.ClipboardMatch</Product>
    <Copyright>Copyright © TransposonY 2017</Copyright>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\..\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\GestureSign.Common\GestureSign.Common.csproj" />
    <EmbeddedResource Update="Properties\Resources.resx" Generator="ResXFileCodeGenerator" LastGenOutput="Resources.Designer.cs" />
    <Compile Update="Properties\Resources.Designer.cs" AutoGen="True" DesignTime="True" DependentUpon="Resources.resx" />
  </ItemGroup>
  <Target Name="CopyPluginToPluginsDirectory" AfterTargets="Build">
    <MakeDir Directories="$(TargetDir)Plugins" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(TargetDir)Plugins" SkipUnchangedFiles="true" />
  </Target>
</Project>
