<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Configurations>Debug;Release;Portable;Centennial;uiAccessRelease</Configurations>
    <Version>9.0.0-alpha.1</Version>
    <AssemblyVersion>9.0.0.0</AssemblyVersion>
    <FileVersion>9.0.0.0</FileVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
