<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Title>GestureSign.PointPatterns</Title>
    <Company>TransposonY</Company>
    <Product>GestureSign.PointPatterns</Product>
    <Copyright>Copyright © TransposonY 2021</Copyright>
  </PropertyGroup>
</Project>
