<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>WindowsInput.snk</AssemblyOriginatorKeyFile>
    <GenerateDocumentationFile Condition="'$(Configuration)' == 'Debug'">true</GenerateDocumentationFile>
    <Title>WindowsInput</Title>
    <Description>Provides a useful wrapper around the User32 SendInput and related native Windows functions for simulating Input Devices in Windows including Keyboard and Mouse.</Description>
    <Company>michaelnoonan</Company>
    <Product>WindowsInput</Product>
    <Copyright>Copyright © michaelnoonan 2010</Copyright>
  </PropertyGroup>
</Project>
