<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>GestureSign.ControlPanel</AssemblyName>
    <RootNamespace>GestureSign.ControlPanel</RootNamespace>
    <Title>GestureSignControlPanel</Title>
    <AssemblyTitle>GestureSignControlPanel</AssemblyTitle>
    <Description>GestureSign Control Panel</Description>
    <Company>TransposonY</Company>
    <Product>GestureSign</Product>
    <ApplicationIcon>Resources\normal.ico</ApplicationIcon>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Centennial'">
    <DefineConstants>$(DefineConstants);ConvertedDesktopApp</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Sentry" Version="6.11.1" />
    <PackageReference Include="System.Management" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GestureSign.Common\GestureSign.Common.csproj" />
    <ProjectReference Include="..\GestureSign.PointPatterns\GestureSign.PointPatterns.csproj" />
    <ProjectReference Include="..\ManagedWinapi\ManagedWinapi.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Defaults\Actions.gsa" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Defaults\Gestures.gest" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Languages\ControlPanel\*.xml" CopyToOutputDirectory="PreserveNewest" />
    <SplashScreen Include="Resources\splash.png" />
    <Resource Include="Resources\normal.ico" />
    <EmbeddedResource Update="Properties\Resources.resx" Generator="ResXFileCodeGenerator" LastGenOutput="Resources.Designer.cs" />
    <Compile Update="Properties\Resources.Designer.cs" AutoGen="True" DesignTime="True" DependentUpon="Resources.resx" />
  </ItemGroup>
</Project>
