<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Title>ManagedWinapi</Title>
    <Product>ManagedWinapi</Product>
    <Copyright>Copyright ©  2005, 2006, 2007, 2008 Michael Schierl</Copyright>
  </PropertyGroup>
</Project>
