<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <RootNamespace>GestureSign.ExtraPlugins.TextCopyer</RootNamespace>
    <AssemblyName>GestureSign.ExtraPlugins.TextCopyer</AssemblyName>
    <Title>TextCopyer</Title>
    <Description>TextCopyer Plugin</Description>
    <Company>TransposonY</Company>
    <Product>TextCopyer</Product>
    <Copyright>Copyright © TransposonY 2017</Copyright>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\..\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\GestureSign.Common\GestureSign.Common.csproj" />
    <None Remove="crosshair.ico" />
    <Resource Include="crosshair.ico" />
  </ItemGroup>
  <Target Name="CopyPluginToPluginsDirectory" AfterTargets="Build">
    <MakeDir Directories="$(TargetDir)Plugins" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(TargetDir)Plugins" SkipUnchangedFiles="true" />
  </Target>
</Project>
