using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Serialization;

namespace GestureSign.InputRecorder.Recording
{
    /// <summary>
    /// Language-neutral capture of everything the daemon's input pipeline reads:
    /// raw HID digitizer reports (+ the device's preparsed data), low-level mouse hook events,
    /// monitor layout and the input-related settings. Serialized as camelCase JSON (*.gsrec.json).
    /// </summary>
    public sealed class InputRecording
    {
        public const int CurrentVersion = 1;

        public int Version { get; set; } = CurrentVersion;

        /// <summary>"recorded" (real hardware) or "synthetic" (generated by tests).</summary>
        public string Source { get; set; }

        public string Description { get; set; }

        public DateTime? RecordedAtUtc { get; set; }

        public string OsVersion { get; set; }

        public RecordedSettings Settings { get; set; } = new RecordedSettings();

        public RecordedEnvironment Environment { get; set; } = new RecordedEnvironment();

        public List<RecordedDevice> Devices { get; set; } = new List<RecordedDevice>();

        public List<RecordedEvent> Events { get; set; } = new List<RecordedEvent>();

        public static readonly JsonSerializerSettings JsonSettings = new JsonSerializerSettings
        {
            ContractResolver = new CamelCasePropertyNamesContractResolver(),
            NullValueHandling = NullValueHandling.Ignore,
            DefaultValueHandling = DefaultValueHandling.Include,
            Formatting = Formatting.Indented,
            Converters = { new StringEnumConverter() },
        };

        public static InputRecording Load(string path)
        {
            return JsonConvert.DeserializeObject<InputRecording>(File.ReadAllText(path, Encoding.UTF8), JsonSettings);
        }

        public void Save(string path)
        {
            File.WriteAllText(path, JsonConvert.SerializeObject(this, JsonSettings), new UTF8Encoding(false));
        }
    }

    /// <summary>Daemon settings (AppConfig) that influence input capture.</summary>
    public sealed class RecordedSettings
    {
        /// <summary>ManagedWinapi.Hooks.MouseActions name, e.g. "Right" or "None".</summary>
        public string DrawingButton { get; set; } = "None";

        /// <summary>GestureSign.Common.Input.DeviceStates flags as integer.</summary>
        public int PenGestureButton { get; set; }

        public bool IgnoreTouchInputWhenUsingPen { get; set; } = true;

        public bool RegisterTouchPad { get; set; } = true;

        public bool RegisterTouchScreen { get; set; } = true;

        public int MinimumPointDistance { get; set; } = 20;

        public bool IsOrderByLocation { get; set; } = true;

        public int InitialTimeout { get; set; }
    }

    public sealed class RecordedEnvironment
    {
        public List<RecordedScreen> Screens { get; set; } = new List<RecordedScreen>();

        /// <summary>Display orientation in degrees: 0, 90, 180 or 270.</summary>
        public int Orientation { get; set; }

        /// <summary>IntPtr.Size of the recording process (4 or 8). Informational; events store bitness-neutral payloads.</summary>
        public int PointerSize { get; set; }
    }

    public sealed class RecordedScreen
    {
        public string DeviceName { get; set; }
        public bool Primary { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    }

    public sealed class RecordedDevice
    {
        /// <summary>Recording-local identifier referenced by <see cref="RecordedEvent.Device"/>.</summary>
        public int Id { get; set; }

        /// <summary>RIDI_DEVICENAME (interface path). Validation rejects names containing ROOT / VIRTUAL_DIGITIZER.</summary>
        public string Name { get; set; }

        public int UsagePage { get; set; }

        /// <summary>RID_DEVICE_INFO_HID.usUsage (0x02 pen, 0x04 touch screen, 0x05 touch pad).</summary>
        public int Usage { get; set; }

        public int VendorId { get; set; }
        public int ProductId { get; set; }
        public int VersionNumber { get; set; }

        /// <summary>Base64 of the RIDI_PREPARSEDDATA blob, consumed by hid.dll HidP_* functions.</summary>
        public string PreparsedData { get; set; }
    }

    public static class RecordedEventTypes
    {
        /// <summary>WM_INPUT carrying RAWHID data.</summary>
        public const string Hid = "hid";

        /// <summary>Low-level mouse hook callback.</summary>
        public const string Mouse = "mouse";

        /// <summary>WM_INPUT_DEVICE_CHANGE.</summary>
        public const string DeviceChange = "deviceChange";
    }

    public static class RecordedMouseMessages
    {
        public const string Down = "down";
        public const string Up = "up";
        public const string Move = "move";
        public const string Wheel = "wheel";
    }

    public sealed class RecordedEvent
    {
        /// <summary>Milliseconds since recording start.</summary>
        public long T { get; set; }

        /// <summary>Environment.TickCount when the event was observed.</summary>
        public int TickCount { get; set; }

        /// <summary>One of <see cref="RecordedEventTypes"/>.</summary>
        public string Type { get; set; }

        /// <summary>Cursor.Position when the event was observed.</summary>
        public int CursorX { get; set; }
        public int CursorY { get; set; }

        // --- hid ---

        /// <summary>RecordedDevice.Id.</summary>
        public int Device { get; set; }

        /// <summary>RAWHID.dwSizHid: bytes per report.</summary>
        public int SizeHid { get; set; }

        /// <summary>RAWHID.dwCount: number of reports in Data.</summary>
        public int Count { get; set; }

        /// <summary>Base64 of RAWHID.bRawData (SizeHid * Count bytes).</summary>
        public string Data { get; set; }

        // --- mouse ---

        /// <summary>One of <see cref="RecordedMouseMessages"/>.</summary>
        public string MouseMessage { get; set; }

        /// <summary>ManagedWinapi.Hooks.MouseActions name for down/up ("Left", "Right", ...).</summary>
        public string Button { get; set; }

        public int X { get; set; }
        public int Y { get; set; }

        /// <summary>MSLLHOOKSTRUCT.mouseData (wheel delta / X button).</summary>
        public int MouseData { get; set; }
    }
}
